---
- user: name=noc
- file:
     state: directory
     path: /home/noc/.ssh
     mode: 0600
     owner: noc
     group: noc
- copy:
      src: auth_key.pub
      dest: /home/noc/.ssh/authorized_keys
      mode: 0600
      owner: noc
      group: noc